---
# handlers file for mosquitto
- name: reload mosquitto
  become: yes
  ansible.builtin.service:
    name: mosquitto
    state: reloaded

- name: restart mosquitto
  become: yes
  ansible.builtin.service:
    name: mosquitto
    state: restarted

- name: start mosquitto
  become: yes
  ansible.builtin.service:
    name: mosquitto
    state: started

- name: stop mosquitto
  become: yes
  ansible.builtin.service:
    name: mosquitto
    state: stopped
